### ISSUE TITLE
création du model UML de la base de donné pour le traitement-archivage des informations nécessaire sur le projet touri-touri

### ISSUE THREAD

**Issue by benaja-bendo** [essengogroup/Api-touri#1]

**Comment by benaja-bendo** [comment]
@StyveLioumba @benaja-bendo @naiss42 @milandou on peut tous revoir le model UML

**Comment by milandou** [comment]
C'est quoi la suite après ici????

**Comment by benaja-bendo** [comment]
### structure de la Base de données

> users

-   id
-   full_name
-   phone
-   profile_picture?
-   email
-   address?
-   isActive?
-   password
-   created_at
-   updated_at

> departements

-   id
-   name
-   description?
-   image_path?
-   created_at
-   updated_at

> sites (= parcours qu'un utilisateur reserve pour sa visite)

-   id
-   departement_id
-   name
-   description
-   price
-   isActive?
-   created_at
-   updated_at

> medias (= images et videos des sites)

-   id
-   site_id
-   image_path
-   default (0 ou 1)
-   created_at
-   updated_at

> sites_dates (= dates disponibles pour les sites)

-   id
-   site_id
-   date
-   start_time
-   end_time
-   created_at
-   updated_at

> activites (= activités à faire sur un site)

-   id
-   name
-   description
-   image_path?
-   created_at
-   updated_at

> activites_sites (= liste des activités liées des sites avec des activités par defaut et des activités personnalisées)

-   id
-   site_id
-   activite_id
-   type (obligatoire, optionnel)-> par defaut obligatoire
-   price?
-   created_at
-   updated_at

> reservations-sites (= réservations des sites)

-   id
-   user_id
-   site_id
-   date_id
-   price
-   nb_personnes
-   status (pending, accepted, refused, canceled)-> par defaut pending
-   commentaire
-   created_at
-   updated_at

> reservations_activites

-   id
-   reservation_id
-   activite_id
-   created_at
-   updated_at

> events (= événements organisés par les sites)

-   id
-   title
-   description
-   image_path?
-   limit_date_reservation
-   limit_date_cancel
-   created_at
-   updated_at

> places_events (= prix des événements organisés par les sites)

-   id
-   event_id
-   price
-   title
-   created_at
-   updated_at

> reservations_events (= réservations des événements)

-   id
-   user_id
-   place_event_id
-   nb_personnes
-   price
-   status (pending, accepted, refused)-> par defaut pending
-   created_at
-   updated_at

> trophets (= trophés gagnés par les utilisateurs)

-   id
-   name
-   description
-   points
-   image_path
-   created_at
-   updated_at

> users_trophets (= trophés gagnés par les utilisateurs)

-   id
-   user_id
-   trophets_id
-   created_at
-   updated_at
